# The definitions in this file should be changed to match your system

# CUDA_DIR   = /usr/local/cuda
CUDA_DIR   = /opt/local/cuda
THRUST_DIR = $(HOME)/code/c_cpp/common/thrust-1.5.1

# LIB_ARCH   = lib
LIB_ARCH   = lib64
GPU_ARCH   = sm_13
# GPU_ARCH   = sm_20

GCC        = gcc
GXX        = g++
AR         = ar
NVCC       = nvcc
DOXYGEN    = doxygen
RM         = rm
ECHO       = echo
MKFLAGS    = 

DEDISP_DEBUG = 0

#.SILENT :
